config/routes.rb
Blog::Application.routes.draw do
  resources :categories

  devise_for :users

    resources :posts do
        resources :comments
    end
    
    
  match 'day' => 'posts#day'
  match 'day_list/:date' => 'posts#day_list'

  match 'month' => 'posts#month'
  match 'month_list/:date' => 'posts#month_list'

  match 'year' => 'posts#year'
  match 'year_list/:date' => 'posts#year_list'

  match 'category_list' => 'posts#category_list'
  match 'cat_list/:cat' => 'posts#cat_list'
  match 'cat_list' => 'posts#cat_list'
  
  match 'category_list' => 'posts#category_list'

  root :to => 'posts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>


    <%= javascript_include_tag "application" %>
  </head>
  <body>

  <div id="header">
  <div id="headerArea">
    <div class="header_txt"><h1>侍エンジニア塾H1タグ</h1></div>

    <div class="header_logo"><%= image_tag 'logo.gif', :size => '120x40' %></div>

    <div id="gnavi">
     <ul id="globalnavi">
      <li><%= link_to 'Home', posts_path %></li>
      <li><%= link_to '新規投稿', new_post_path %></li>
      <li><%= link_to 'カテゴリ一覧', category_list_path %></li>
      <li><%= link_to '日別アーカイブ', day_path %></li>
      <li><%= link_to '月別アーカイブ', month_path %></li>
      <li><%= link_to '年別アーカイブ', year_path %></li>
      </ul>
    </div>
    <!-- end div#gnavi -->

  </div><!-- end div#headerArea -->
  </div><!-- end div#header -->


  <div id="content" class="floatwrap">
  <div id="contentArea" class="floatwrap">

  <div id="main" class="floatwrap">

<%= yield %>

  </div><!-- end div#main -->

  <div id="side" class="floatwrap">
  <p>sidebar</p>
  </div><!-- end div#side -->


  </div><!-- end div#contentArea -->
  </div><!-- end div#content -->

    </div> <!-- /container -->


  <div id="footer">
  <div id="footerArea" class="floatwrap">

    <div class="footer_navi">
      <ul>
      <li><%= link_to 'Home', posts_path %></li>
      <li><%= link_to '新規投稿', new_post_path %></li>
      </ul>
    </div>

    <div class="footer_navi">
      <ul>
      <li><%= link_to '日別アーカイブ', day_path %></li>
      <li><%= link_to '月別アーカイブ', month_path %></li>
      <li><%= link_to '年別アーカイブ', year_path %></li>
      </ul>
    </div>

    <div class="footer_navi">
      <ul>
        <li><%= link_to 'カテゴリ一覧', category_list_path %></li>
        <li><%= link_to 'カテゴリ管理', categories_path %></li>
      </ul>
    </div>

    <div class="footer_logo">
      <p>〒150-0002<br>
        東京都渋谷区渋谷1-1-1<br>
        TEL:03-1234-5678</p>
    </div>

  <div class="footer_copy">Copyright (C) 2014 <a href="/">ふなっしー</a> All Rights Reserved.</div>

  </div><!-- end div#footerArea -->
  </div><!-- end div#footer -->


  </body>
</html>